### ISSUE TITLE
Service Timeout

### ISSUE THREAD

**Issue by Binternet** [pelias/placeholder#106]
After enabling the service on pelias.json and calling the API it throws a timeout error:

`[placeholder] http://localhost:4100/parser/search?text=israel&lang=eng: {"timeout":250,"code":"ECONNABORTED","errno":"ETIME","retries":3}`

**Comment by missinglink** [comment]
Hi Lior,

It's possible to configure the timeout as per comments on this issue (for a different service): https://github.com/pelias/wof-admin-lookup/issues/192

Although that's a cosmetic fix :(

There is an issue open to do some development work in order to reduce latency in https://github.com/pelias/placeholder/issues/102

Although, as noted in that issue, 'slow' for the placeholder service is around 30ms, I'm guessing that your response times are slower when the service is under a high concurrency load?

So three options:
1. Increase the timeout in the config
2. Scale the service to handle more concurrency
3. Wait for issue #102 to be resolved, or implement one of the two performance optimizations mentioned in that issue (new endpoint or/ client-side cache).
