### ISSUE TITLE
Inconsistent behavior in the presence of non ascii characters

### ISSUE THREAD

**Issue by azaroth42** [pelias/placeholder#203]
**Describe the bug**

Placeholder does not deal with unicode characters consistently.

For example:   "z︠h︡ovkva, ukraine" is https://spelunker.whosonfirst.org/id/101876827/  
and "zhovka, ukraine" if submitted to the API works as expected. So does "Žovkva, ukraine", as does "Żółkiew"

Are there some characters that we should strip, and others that we can leave in? Is there a particular unicode normal form that should be used? NFC?

Would be good to describe good practices in the documentation at least?

**Comment by missinglink** [comment]
Hi Rob, It's been a while since we wrote this lib and I'm trying to remember what normalisation is performed exactly.

You can view the [analysis code](https://github.com/pelias/placeholder/blob/master/lib/analysis.js) and [tests](https://github.com/pelias/placeholder/blob/master/test/lib/analysis.js) yourself and see what it's doing, it uses a module called [remove-accents](https://github.com/tyxla/remove-accents) to ASCII-fold the tokens, so it's not very advanced in that regard.

We don't have anyone on the team who speaks Cyrillic languages so they are probably not well supported, if you have some changes you'd like to make please open a PR so we can discuss.

The main Pelias API server has [a unicode module](https://github.com/pelias/api/blob/master/helper/unicode.js) / [tests](https://github.com/pelias/api/blob/master/test/unit/helper/unicode.js) which handles the low-level encoding and normalization, we could add something similar to convert strings to NFKC at both index time and search time.

**Comment by missinglink** [comment]
I had a look at including `NFKC` normalisation, the results for Ukrainian specifically were:

> note: `<` refers to the `master` branch and `>` refers to the new `unicode` branch

```diff
14d13
< 85632181|ukr|variant|мʼянма
37,38c36,37
< 85632227|ukr|variant|танзанія обʼєднана республіка
< 85632227|ukr|variant|обʼєднана республіка танзанія
---
> 85632227|ukr|variant|танзанія обєднана республіка
> 85632227|ukr|variant|обєднана республіка танзанія
230d228
< 85632573|ukr|variant|обʼєднані арабські емірати
336d333
< 85632763|ukr|variant|вʼєтнам
58299d58295
< 101858717|ukr|variant|ові́діополь
84895c84891
< 102022183|ukr|preferred|коби́ла
---
> 102022183|ukr|preferred|кобила
146198c146194
< 404528747|ukr|variant|лабрадо́рське море
---
> 404528747|ukr|variant|лабрадорське море
146243c146239
< 404528839|ukr|preferred|ла́птєвих мо́ре
---
> 404528839|ukr|preferred|лаптєвих море
157648c157644
< 890442049|ukr|preferred|сисопхо́н
---
> 890442049|ukr|preferred|сисопхон
175234c175230
< 1125774151|ukr|preferred|kral̕ovany
---
> 1125774151|ukr|preferred|kralovany
178694c178690
< 1125797615|ukr|preferred|michal̕any
---
> 1125797615|ukr|preferred|michalany
179447c179443
< 1125803747|ukr|preferred|vigl̕as
---
> 1125803747|ukr|preferred|viglas
181955c181951
< 1125823321|ukr|preferred|sol̕
---
> 1125823321|ukr|preferred|sol
184609,184610c184605
< 1125843295|ukr|preferred|ові́діополь
< 1125843295|ukr|variant|овідіополь
---
> 1125843295|ukr|preferred|овідіополь
193109c193104
< 1125906195|ukr|preferred|kl̕ak
---
> 1125906195|ukr|preferred|klak
200887c200882
< 1125958721|ukr|preferred|medved̕ov
---
> 1125958721|ukr|preferred|medvedov
218075,218076c218070
< 1158846601|ukr|variant|сенпʼєр і мікелон
< 1158846601|ukr|variant|сен пʼєр і мікелон
---
> 1158846601|ukr|variant|сен пєр і мікелон
263222c263216
< 1226340469|ukr|variant|пра́вдівка
---
> 1226340469|ukr|variant|правдівка
324566d324559
< 1276225563|ukr|variant|петрі́вське
349744,349745c349737,349738
< 1293095387|ukr|variant|абаде́йеташк
< 1293095387|ukr|variant|абаде́ йе ташк
---
> 1293095387|ukr|variant|абадейеташк
> 1293095387|ukr|variant|абаде йе ташк
349748,349749c349741,349742
< 1293095387|ukr|variant|абаде́іташк
< 1293095387|ukr|variant|абаде́ і ташк
---
> 1293095387|ukr|variant|абадеіташк
> 1293095387|ukr|variant|абаде і ташк
```

**Comment by missinglink** [comment]
see: https://github.com/pelias/placeholder/pull/207

**Comment by missinglink** [comment]
I'm closing this issue since the description isn't clear as to the failure condition or the expected success criteria.
I can only assume the bug is that the input `z︠h︡ovkva` doesn't match `zhovka`.

https://github.com/pelias/placeholder/pull/207 will improve the unicode handling so that input can be in *any* normalisation form which will be converted internally before querying.
