### ISSUE TITLE
Unicode problems for data creation?

### ISSUE THREAD

**Issue by karussell** [pelias/placeholder#96]
When I played with the demo I noticed a strange `&` that got appended and some unicode problems. But as not all results have this problem, there might be something with data creation problems regarding unicode?

![image](https://user-images.githubusercontent.com/129644/38777421-b139cf46-40a7-11e8-8ed8-51fca021f6e9.png)

Also looking for locations with unicode like "zeißig" then it does not work. It should give [this suburb](https://graphhopper.com/maps/?point=Zei%C3%9Fig).

**Comment by karussell** [comment]
Hmmh, "Berlin Neukölln" works (setting it to German https://parser.synergy.io/demo/#deu)

**Comment by missinglink** [comment]
The '&' symbol here is just a visual symbol to signify that the input it autocomplete and has not been completed.

A '*' symbol would probably be more intuitive.

Internally I'm using `\x26` which I thought was a non-printing character but it's actually '&'.

It doesn't really matter because it's doesn't affect the parse at all, but I might change that to `x1a` (decimal 26) which is what I was probably originally intending, the 'substitute character', which makes more sense here.

**Comment by missinglink** [comment]
The errors below are unfortunately in the data: https://spelunker.whosonfirst.org/id/102063431/

I'll bring it up with the data team or you can file a bug directly at https://github.com/whosonfirst-data/whosonfirst-data
